# Description
# ===========
# This playbook creates an Azure Windows VM with public IP. It also cobnfigures the machine to be accessible via Ansible using WinRM.
# This playbook originally comes from @jborean93 (https://github.com/jborean93/ansible-win-demos)
- name: provision new azure host
  hosts: localhost
  vars:
    location: westeurope
    project_prefix: "ansiblehack"
    resourcegroup_name: "{{project_prefix}}-rg"
    virtualnetwork_name: "{{project_prefix}}-vnet"
    subnet_name: "{{project_prefix}}-subnet"
    securitygroup_name: "{{project_prefix}}-nsg"

    vm_admin: "dgg"
    vm_password: "hack@123456"

    host_vm_prefix: "host"
    host_count: 2

  tasks:
    - name: "Create {{ resourcegroup_name }} Resource Group"
      azure_rm_resourcegroup:
        name: "{{ resourcegroup_name }}"
        location: "{{ location }}"

    - name: "Create {{virtualnetwork_name}} Virtual Network"
      azure_rm_virtualnetwork:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ virtualnetwork_name }}"
        address_prefixes: "10.0.0.0/16"

    - name: "Create {{subnet_name}} Subnet in {{virtualnetwork_name}} for host"
      azure_rm_subnet:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ subnet_name }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ virtualnetwork_name }}"
  
    - name: Create public IP address for each host
      azure_rm_publicipaddress:
        resource_group: "{{ resourcegroup_name }}"
        allocation_method: Static
        name: "{{ item }}_ip"
      with_sequence: "count={{ host_count }} format={{ host_vm_prefix }}%02x"

    - name: "Create {{securitygroup_name}} security rules for hosts"
      azure_rm_securitygroup:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ securitygroup_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create a network interface for each VM
      azure_rm_networkinterface:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ item }}_nic"
        virtual_network: "{{ virtualnetwork_name }}"
        subnet: "{{ subnet_name }}"
        security_group: "{{ securitygroup_name }}"
        ip_configurations:
          - name: "ipconfig"
            public_ip_address_name: "{{item}}_ip"
            primary: True
      with_sequence: "count={{ host_count }} format={{ host_vm_prefix }}%02x"

    - name: Create host VMs
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup_name }}"
        name: "{{ item }}-vm"
        vm_size: Standard_DS1_v2
        admin_username: "{{ vm_admin }}"
        admin_password: "{{ vm_password }}"
        ssh_public_keys:
          - path: "/home/{{ vm_admin }}/.ssh/authorized_keys"
            key_data: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"        
        network_interfaces: "{{ item }}_nic"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
      with_sequence: "count={{ host_count }} format={{ host_vm_prefix }}%02x"