- hosts: hosts
  become: true
  roles:
    - role: geerlingguy.ansible
  vars:
#    user: "developer"
    # To create the password use: 
    # ansible all -i localhost, -m debug -a "msg={{ 'mypassword' | password_hash('sha512', 'mysecretsalt') }}"
#    password: "$6$mysecretsalt$zav3we8Mej2y5GPXs7e6gJcQuZqfQYMnfCyR5dKdlU2UHXWv3/AjPB/ORFtK0YDViU6eyfSPBeaLC/DRXRfAT/"
  tasks:
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - python-pip
        - tree
    - name: install pywinrm
      pip:    
        name: "pywinrm"